export interface DataI {
  "Product Details": string;
  SKU: string;
  key: string;
  Title: string;
  Description: string;
  "Handling Time": string;
  "Standard Price": string;
  Inventory: string;
  "Product ID": string;
  "Product ID Type": string;
  "Country Of Origin": string;
  Condition: string;
  "Sale Price": string;
  "Sale Start Date": string;
  "Sale End Date": string;
  "Item Weight": string;
  "Item Weight Unit": string;
  "Batteries Included": string;
  "Dangerous Goods Regulations": string;
  "Fulfillment Centre ID": string;
}

const data : DataI[] = [
  {
    "Product Details": "Apple iPhone 13 (128GB) - Sta...",
    SKU: "4772138942699",
    key: "4772138942699",
    Title: "The 3p Fulfilled Snowboard",
    Description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente, voluptatibus!",
    "Handling Time": "4 days",
    "Standard Price": "INR 1200",
    Inventory: "500",
    "Product ID": "1234444NB",
    "Product ID Type": "ISBN",
    "Country Of Origin": "Japan",
    Condition: "Offers",
    "Sale Price": "INR 250",
    "Sale Start Date": "11/08/2023",
    "Sale End Date": "12/08/2023",
    "Item Weight": "200",
    "Item Weight Unit": "gm",
    "Batteries Included": "1",
    "Dangerous Goods Regulations": "yes",
    "Fulfillment Centre ID": "UR1233524254",
  },
  {
    "Product Details": "Apple iPhone 13 (128GB)",
    SKU: "4772138942650",
    key: "4772138942650",
    Title: "The Latest iPhone",
    Description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente, voluptatibus!",
    "Handling Time": "2 days",
    "Standard Price": "INR 8000",
    Inventory: "1000",
    "Product ID": "0987654NB",
    "Product ID Type": "ISBN",
    "Country Of Origin": "USA",
    Condition: "New",
    "Sale Price": "INR 7000",
    "Sale Start Date": "11/20/2023",
    "Sale End Date": "12/20/2023",
    "Item Weight": "150",
    "Item Weight Unit": "gm",
    "Batteries Included": "1",
    "Dangerous Goods Regulations": "no",
    "Fulfillment Centre ID": "UR1233524257",
  },
  {
    "Product Details": "Samsung Galaxy S23 Ultra (512GB)",
    SKU: "4772138942651",
    key: "4772138942651",
    Title: "The Ultimate Android Phone",
    Description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente, voluptatibus!",
    "Handling Time": "3 days",
    "Standard Price": "INR 12000",
    Inventory: "500",
    "Product ID": "1234567NB",
    "Product ID Type": "ISBN",
    "Country Of Origin": "South Korea",
    Condition: "Refurbished",
    "Sale Price": "INR 10000",
    "Sale Start Date": "11/22/2023",
    "Sale End Date": "12/22/2023",
    "Item Weight": "200",
    "Item Weight Unit": "gm",
    "Batteries Included": "1",
    "Dangerous Goods Regulations": "no",
    "Fulfillment Centre ID": "UR1233524258",
  },
  {
    "Product Details": "Sony PlayStation 5 - Console",
    SKU: "4772138942652",
    key: "4772138942652",
    Title: "The Next-Gen Gaming Console",
    Description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente, voluptatibus!",
    "Handling Time": "4 days",
    "Standard Price": "INR 50000",
    Inventory: "200",
    "Product ID": "3456789NB",
    "Product ID Type": "ISBN",
    "Country Of Origin": "Japan",
    Condition: "New",
    "Sale Price": "INR 45000",
    "Sale Start Date": "11/25/2023",
    "Sale End Date": "12/25/2023",
    "Item Weight": "5000",
    "Item Weight Unit": "gm",
    "Batteries Included": "0",
    "Dangerous Goods Regulations": "no",
    "Fulfillment Centre ID": "UR1233524259",
  },
  {
    "Product Details": "Nintendo Switch - OLED Model",
    SKU: "4772138942653",
    key: "4772138942653",
    Title: "The Ultimate Portable Gaming Console",
    Description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente, voluptatibus!",
    "Handling Time": "2 days",
    "Standard Price": "INR 30000",
    Inventory: "300",
    "Product ID": "5678901NB",
    "Product ID Type": "ISBN",
    "Country Of Origin": "Japan",
    Condition: "Refurbished",
    "Sale Price": "INR 25000",
    "Sale Start Date": "11/27/2023",
    "Sale End Date": "12/25/2023",
    "Item Weight": "5000",
    "Item Weight Unit": "gm",
    "Batteries Included": "0",
    "Dangerous Goods Regulations": "no",
    "Fulfillment Centre ID": "UR1233524259",
  },
  {
    "Product Details": "The 3p Fulfilled Snowboard",
    SKU: "4772138942647",
    key: "4772138942647",
    Title: "The Powder Board",
    Description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente, voluptatibus!",
    "Handling Time": "4 days",
    "Standard Price": "INR 1200",
    Inventory: "500",
    "Product ID": "1234444NB",
    "Product ID Type": "ISBN",
    "Country Of Origin": "Japan",
    Condition: "Offers",
    "Sale Price": "INR 250",
    "Sale Start Date": "11/08/2023",
    "Sale End Date": "12/08/2023",
    "Item Weight": "200",
    "Item Weight Unit": "gm",
    "Batteries Included": "1",
    "Dangerous Goods Regulations": "yes",
    "Fulfillment Centre ID": "UR1233524254",
  },
  {
    "Product Details": "The All-Mountain Board",
    SKU: "4772138942648",
    key: "4772138942648",
    Title: "The All-Mountain Board",
    Description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente, voluptatibus!",
    "Handling Time": "3 days",
    "Standard Price": "INR 1500",
    Inventory: "300",
    "Product ID": "5678234NB",
    "Product ID Type": "ISBN",
    "Country Of Origin": "South Korea",
    Condition: "New",
    "Sale Price": "INR 350",
    "Sale Start Date": "11/10/2023",
    "Sale End Date": "12/10/2023",
    "Item Weight": "300",
    "Item Weight Unit": "gm",
    "Batteries Included": "1",
    "Dangerous Goods Regulations": "no",
    "Fulfillment Centre ID": "UR1233524255",
  },
  {
    "Product Details": "The Next-Gen Gaming Console",
    SKU: "4772138942649",
    key: "4772138942649",
    Title: "The Next-Gen Gaming Console",
    Description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente, voluptatibus!",
    "Handling Time": "4 days",
    "Standard Price": "INR 4000",
    Inventory: "200",
    "Product ID": "9876543NB",
    "Product ID Type": "ISBN",
    "Country Of Origin": "Japan",
    Condition: "Refurbished",
    "Sale Price": "INR 3000",
    "Sale Start Date": "11/15/2023",
    "Sale End Date": "12/15/2023",
    "Item Weight": "500",
    "Item Weight Unit": "gm",
    "Batteries Included": "0",
    "Dangerous Goods Regulations": "no",
    "Fulfillment Centre ID": "UR1233524256",
  },
  {
    "Product Details": "Microsoft Surface Laptop Studio",
    SKU: "4772138942655",
    key: "4772138942655",
    Title: "The Multi-Mod Switchable Laptop",
    Description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente, voluptatibus!",
    "Handling Time": "5 days",
    "Standard Price": "INR 75000",
    Inventory: "200",
    "Product ID": "9876542NB",
    "Product ID Type": "ISBN",
    "Country Of Origin": "USA",
    Condition: "Refurbished",
    "Sale Price": "INR 65000",
    "Sale Start Date": "11/29/2023",
    "Sale End Date": "12/29/2023",
    "Item Weight": "2500",
    "Item Weight Unit": "gm",
    "Batteries Included": "0",
    "Dangerous Goods Regulations": "no",
    "Fulfillment Centre ID": "UR1233524258",
  },
  {
    "Product Details": "Dell XPS 15 Laptop",
    SKU: "4772138942656",
    key: "4772138942656",
    Title: "The Ultimate Performance Laptop",
    Description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente, voluptatibus!",
    "Handling Time": "4 days",
    "Standard Price": "INR 90000",
    Inventory: "200",
    "Product ID": "5678902NB",
    "Product ID Type": "ISBN",
    "Country Of Origin": "China",
    Condition: "Refurbished",
    "Sale Price": "INR 80000",
    "Sale Start Date": "12/05/2023",
    "Sale End Date": "12/20/2023",
    "Item Weight": "1800",
    "Item Weight Unit": "gm",
    "Batteries Included": "1",
    "Dangerous Goods Regulations": "no",
    "Fulfillment Centre ID": "UR1233524259",
  },
  {
    "Product Details": "Bose QuietComfort 35 II Headphones",
    SKU: "4772138942658",
    key: "4772138942658",
    Title: "The Comfortable Noise-Cancelling Headphones",
    Description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente, voluptatibus!",
    "Handling Time": "3 days",
    "Standard Price": "INR 22000",
    Inventory: "300",
    "Product ID": "5678904NB",
    "Product ID Type": "ISBN",
    "Country Of Origin": "USA",
    Condition: "Refurbished",
    "Sale Price": "INR 18000",
    "Sale Start Date": "12/12/2023",
    "Sale End Date": "01/12/2023",
    "Item Weight": "2000",
    "Item Weight Unit": "gm",
    "Batteries Included": "1",
    "Dangerous Goods Regulations": "no",
    "Fulfillment Centre ID": "UR1233524260",
  },
  {
    "Product Details": "Sony WH-1000XM4 Headphones",
    SKU: "4772138942659",
    key: "4772138942659",
    Title: "The Noise-Cancelling Headphones for Audiophiles",
    Description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente, voluptatibus!",
    "Handling Time": "2 days",
    "Standard Price": "INR 28000",
    Inventory: "200",
    "Product ID": "3456789NB",
    "Product ID Type": "ISBN",
    "Country Of Origin": "Japan",
    Condition: "Refurbished",
    "Sale Price": "INR 23000",
    "Sale Start Date": "12/19/2023",
    "Sale End Date": "01/05/2024",
    "Item Weight": "2200",
    "Item Weight Unit": "gm",
    "Batteries Included": "1",
    "Dangerous Goods Regulations": "no",
    "Fulfillment Centre ID": "UR1233524261",
  },
  {
    "Product Details": "Fitbit Sense smartwatch",
    SKU: "4772138942660",
    key: "4772138942660",
    Title: "The Smartwatch for Health and Fitness",
    Description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente, voluptatibus!",
    "Handling Time": "2 days",
    "Standard Price": "INR 25000",
    Inventory: "100",
    "Product ID": "9876545NB",
    "Product ID Type": "ISBN",
    "Country Of Origin": "China",
    Condition: "New",
    "Sale Price": "INR 20000",
    "Sale Start Date": "11/25/2023",
    "Sale End Date": "12/25/2023",
    "Item Weight": "1000",
    "Item Weight Unit": "gm",
    "Batteries Included": "1",
    "Dangerous Goods Regulations": "no",
    "Fulfillment Centre ID": "UR1233524262",
  },
  {
    "Product Details": "Acer Nitro 5 Gaming Laptop",
    SKU: "4772138942661",
    key: "4772138942661",
    Title: "The Affordable Gaming Laptop",
    Description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente, voluptatibus!",
    "Handling Time": "3 days",
    "Standard Price": "INR 60000",
    Inventory: "300",
    "Product ID": "9876544NB",
    "Product ID Type": "ISBN",
    "Country Of Origin": "Taiwan",
    Condition: "Refurbished",
    "Sale Price": "INR 52000",
    "Sale Start Date": "11/28/2023",
    "Sale End Date": "12/28/2023",
    "Item Weight": "2500",
    "Item Weight Unit": "gm",
    "Batteries Included": "1",
    "Dangerous Goods Regulations": "no",
    "Fulfillment Centre ID": "UR1233524263",
  },
  {
    "Product Details": "HP Spectre x360 Laptop",
    SKU: "4772138942662",
    key: "4772138942662",
    Title: "The Convertible Laptop for On-The-Go Productivity",
    Description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente, voluptatibus!",
    "Handling Time": "4 days",
    "Standard Price": "INR 85000",
    Inventory: "100",
    "Product ID": "5678905NB",
    "Product ID Type": "ISBN",
    "Country Of Origin": "USA",
    Condition: "New",
    "Sale Price": "INR 72000",
    "Sale Start Date": "11/30/2023",
    "Sale End Date": "12/30/2023",
    "Item Weight": "1800",
    "Item Weight Unit": "gm",
    "Batteries Included": "1",
    "Dangerous Goods Regulations": "no",
    "Fulfillment Centre ID": "UR1233524264",
  },
  {
    "Product Details": "Samsung Galaxy Book Flex 2 5G",
    SKU: "4772138942668",
    key: "4772138942668",
    Title: "The Convertible Laptop for On-The-Go Productivity",
    Description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente, voluptatibus!",
    "Handling Time": "2 days",
    "Standard Price": "INR 110000",
    Inventory: "50",
    "Product ID": "5678908NB",
    "Product ID Type": "ISBN",
    "Country Of Origin": "South Korea",
    Condition: "Refurbished",
    "Sale Price": "INR 93000",
    "Sale Start Date": "12/07/2023",
    "Sale End Date": "12/22/2023",
    "Item Weight": "1600",
    "Item Weight Unit": "gm",
    "Batteries Included": "1",
    "Dangerous Goods Regulations": "no",
    "Fulfillment Centre ID": "UR1233524268",
  },
  {
    "Product Details": "Google Pixelbook Go",
    SKU: "4772138942669",
    key: "4772138942669",
    Title: "The Lightweight and Stylish Laptop for Minimalist",
    Description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente, voluptatibus!",
    "Handling Time": "3 days",
    "Standard Price": "INR 75000",
    Inventory: "300",
    "Product ID": "3456791NB",
    "Product ID Type": "ISBN",
    "Country Of Origin": "Taiwan",
    Condition: "New",
    "Sale Price": "INR 64000",
    "Sale Start Date": "12/14/2023",
    "Sale End Date": "12/30/2023",
    "Item Weight": "1200",
    "Item Weight Unit": "gm",
    "Batteries Included": "1",
    "Dangerous Goods Regulations": "no",
    "Fulfillment Centre ID": "UR1233524269",
  },
  {
    "Product Details": "Razer Blade 17 Gaming Laptop",
    SKU: "4772138942670",
    key: "4772138942670",
    Title: "The High-End Gaming Laptop for Serious",
    Description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente, voluptatibus!",
    "Handling Time": "5 days",
    "Standard Price": "INR 140000",
    Inventory: "200",
    "Product ID": "5678909NB",
    "Product ID Type": "ISBN",
    "Country Of Origin": "USA",
    Condition: "Refurbished",
    "Sale Price": "INR 120000",
    "Sale Start Date": "12/21/2023",
    "Sale End Date": "01/10/2024",
    "Item Weight": "3500",
    "Item Weight Unit": "gm",
    "Batteries Included": "1",
    "Dangerous Goods Regulations": "no",
    "Fulfillment Centre ID": "UR1233524270",
  },
];

export default data;
