import React from "react";
import {
  Zap,
  ZapOff,
  ZoomIn,
  ZoomOut,
  YouTube,
  Xsquare,
  Xoctagon,
  Xcircle,
  Wind,
  WifiOff,
  Wifi,
  Watch,
  VolumeX,
  Volume2,
  Volume1,
  Volume,
  VoiceMail,
  VideoOff,
  VideoOn,
  Users,
  UserX,
  UserPlus,
  UserMinus,
  UserCheck,
  User,
  UploadCloud,
  Upload,
  Unlock,
  Underline,
  Umbrella,
  Type,
  Twitter,
  Twitch,
  Tv,
  Truck,
  Triangle,
  TrendingUp,
  TrendingDown,
  Trello,
  Trash2,
  Trash,
  Tool,
  ToggleRight,
  ToggleLeft,
  ThumbsUp,
  ThumbsDown,
  Thermometer,
  Terminal,
  Target,
  TagIcon,
  Tablet,
  Table,
  Sunset,
  Sunrise,
  Sun,
  StopCircle,
  Star,
  Square,
  Speaker,
  Smile,
  Smartphone,
  Sliders,
  Slash,
  Slack,
  SkipForward,
  SkipBack,
  Shuffle,
  ShoppingCart,
  ShoppingBag,
  ShieldOff,
  Shield,
  Share2,
  Share,
  Settings,
  Server,
  Send,
  Search,
  Scissors,
  Save,
  Rss,
  RotateCw,
  RotateCcw,
  Rewind,
  Repeat,
  RefreshCw,
  RefreshCcw,
  RadioIcon,
  Printer,
  Power,
  Pocket,
  PlusSquare,
  PlusCircle,
  Plus,
  PlayCircle,
  Play,
  PieChart,
  PhoneOutgoing,
  PhoneOff,
  PhoneMissed,
  PhoneIncoming,
  X,
  PhoneCall,
  Phone,
  Percent,
  PenTool,
  PauseCircle,
  Pause,
  PaperClip,
  Package,
  Octagon,
  Navigation2,
  Navigation,
  Music,
  Move,
  MousePointer,
  MoreVertical,
  MoreHorizontal,
  Moon,
  Monitor,
  MinusSquare,
  MinusCircle,
  Minus,
  Minimize2,
  Minimize,
  MicOff,
  Mic,
  MessageSquare,
  MessageCircle,
  Menu,
  Meh,
  Maximize2,
  Maximize,
  MapPin,
  Map,
  Mail,
  Logout,
  LogIn,
  Lock,
  LoaderIcon,
  ListIcon,
  LinkedIn,
  Link2,
  Link,
  LifeBuoy,
  Layout,
  Layers,
  Key,
  Italic,
  ProductDelivery,
  Discount,
  Billing,
  ProductSuccessful,
  Campaign,
  Analytics,
  Store,
  Payment1,
  Theme,
  Transaction,
  BulkOrders,
  BulkProducts,
  AbandonedCart,
  Activities,
  AddProduct,
  Apps,
  Wallet,
  ReturnProduct,
  List1,
  Money,
  Rupee,
  Yen,
  Bitcoin,
  Dollar,
  Euro,
  Pound,
  Ruble,
  Session,
  Backspace,
  Checklist,
  DataVisualization,
  DragAndDrop,
  Drag,
  Exchange,
  Inventory,
  Newsletter,
  Hint,
  Event,
  OnlineStore,
  Logout1,
  OrderStatus,
  CartAdded,
  Tracking,
  WriteReview,
  Ticket,
  Bank,
  Report,
  Pin,
  Refund,
  Member,
  Barcode,
  BarChart1,
  BarChart2,
  Variants,
  Bug,
  Language,
  Categories,
  Connect,
  CardEdit,
  Embed,
  CardLock,
  Instagram,
  Info,
  Inbox,
  Image,
  Home,
  Hexagon,
  HelpCircle,
  Heart,
  HeadPhones,
  Hash,
  HardDrive,
  Grid,
  Globe,
  Gitlab,
  Github,
  GitPullRequest,
  GitMerge,
  GitCommit,
  GitBranch,
  Gift,
  Frown,
  Framer,
  FolderPlus,
  FolderMinus,
  Folder,
  Flag,
  FilterIcon,
  Film,
  FileText,
  FilePlus,
  FileMinus,
  File,
  Figma,
  Feather,
  FastForward,
  Facebook,
  EyeOff,
  Eye,
  ExternalLink,
  Edit3,
  Edit2,
  Edit,
  Droplet,
  Dribble,
  DownloadCloud,
  Download,
  DollarSign,
  DivideSquare,
  DivideCircle,
  Divide,
  Disc,
  Delete,
  Database,
  Crosshair,
  Crop,
  CreditCard,
  Cpu,
  CornerUpRight,
  CornerUpLeft,
  CornerRightUp,
  CornerRightDown,
  CornerLeftUp,
  CornerLeftDown,
  CornerDownRight,
  CornerDownLeft,
  Copy,
  Compass,
  Command,
  Columns,
  Coffee,
  CodeSandBox,
  CodePen,
  Code,
  CloudSnow,
  CloudRain,
  CloudOff,
  CloudLightning,
  CloudDrizzle,
  Cloud,
  Clock,
  Clipboard,
  Circle,
  Chrome,
  ChevronsUp,
  ChevronsRight,
  ChevronLeft,
  ChevronsDown,
  ChevronUp,
  CheckSquare,
  CheckCircle,
  Check,
  Cast,
  CameraOff,
  Camera,
  Calender,
  BriefCase,
  Box,
  ChevronDown,
  ChevronsLeft,
  ChevronRight,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  Anchor,
  Aperture,
  Archive,
  Bell,
  BellOff,
  Activity,
  Award,
  Bluetooth,
  PhoneForwarded,
  SidebarIcon,
  Bookmark,
  Book,
  BankOpen,
  Bold,
  BatteryCharging,
  Battery,
  AtSign,
  ArrowUpRight,
  ArrowUpLeft,
  ArrowUpCircle,
  ArrowUp,
  ArrowRightCircle,
  ArrowRight,
  ArrowLeftCircle,
  ArrowLeft,
  ArrowDownRight,
  ArrowDownLeft,
  ArrowDownCircle,
  ArrowDown,
  Airplay,
  Payment,
} from "./Icons";

export const IconsData = ({ ...rest }) => {
  const Icons = [
    {
      icon: <ZoomIn {...rest} />,
      name: "ZoomIn",
      data: ["zoomin", "lens", "in"],
    },
    {
      icon: <ZoomOut {...rest} />,
      name: "ZoomOut",
      data: ["zoomout", "out"],
    },
    {
      icon: <ZapOff {...rest} />,
      name: "ZapOff",
      data: ["zapoff"],
    },
    {
      icon: <BarChart1 {...rest} />,
      name: "BarChart1",
      data: ["barchart"],
    },
    {
      icon: <BarChart2 {...rest} />,
      name: "BarChart2",
      data: ["barchart"],
    },
    {
      icon: <Zap {...rest} />,
      name: "Zap",
      data: ["zap"],
    },
    {
      icon: <Bold {...rest} />,
      name: "Bold",
      data: ["bold"],
    },
    {
      icon: <BatteryCharging {...rest} />,
      name: "BatteryCharging",
      data: ["batterycharging"],
    },
    {
      icon: <ArrowUpRight {...rest} />,
      name: "ArrowUpRight",
      data: ["arrow", "right", "up"],
    },
    {
      icon: <ArrowUpLeft {...rest} />,
      name: "ArrowUpLeft",
      data: ["arrow", "left", "up"],
    },
    {
      icon: <ArrowUpCircle {...rest} />,
      name: "ArrowUpCircle",
      data: ["arrow", "up", "circle"],
    },
    {
      icon: <ArrowUp {...rest} />,
      name: "ArrowUp",
      data: ["arrow", "up"],
    },
    {
      icon: <ArrowRight {...rest} />,
      name: "ArrowRight",
      data: ["arrow", "right"],
    },
    {
      icon: <ArrowLeft {...rest} />,
      name: "ArrowLeft",
      data: ["arrow", "left"],
    },
    {
      icon: <ArrowRightCircle {...rest} />,
      name: "ArrowRightCircle",
      data: ["arrow", "right", "circle"],
    },
    {
      icon: <ArrowDownRight {...rest} />,
      name: "ArrowDownRight",
      data: ["arrow", "right", "down"],
    },
    {
      icon: <ArrowDownLeft {...rest} />,
      name: "ArrowDownRight",
      data: ["arrow", "left", "down"],
    },
    {
      icon: <ArrowLeftCircle {...rest} />,
      name: "ArrowLeftCircle",
      data: ["arrow", "left", "circle"],
    },
    {
      icon: <ArrowDown {...rest} />,
      name: "ArrowDown",
      data: ["arrow", "down"],
    },
    {
      icon: <Airplay {...rest} />,
      name: "Airplay",
      data: ["Airplay"],
    },
    {
      icon: <ArrowDownCircle {...rest} />,
      name: "ArrowDownCircle",
      data: ["arrow", "down", "circle"],
    },
    {
      icon: <Battery {...rest} />,
      name: "Battery",
      data: ["battery"],
    },
    {
      icon: <AtSign {...rest} />,
      name: "AtSign",
      data: ["atsign"],
    },
    {
      icon: <Upload {...rest} />,
      name: "Upload",
      data: ["upload"],
    },
    {
      icon: <Layers {...rest} />,
      name: "Layers",
      data: ["layers"],
    },
    {
      icon: <Key {...rest} />,
      name: "Key",
      data: ["key"],
    },
    {
      icon: <YouTube {...rest} />,
      name: "YouTube",
      data: ["youtube", "videoplayer"],
    },
    {
      icon: <Xsquare {...rest} />,
      name: "Xsquare",
      data: ["Xsquare"],
    },
    {
      icon: <Xoctagon {...rest} />,
      name: "Xoctagon",
      data: ["xoctagon"],
    },
    {
      icon: <Xcircle {...rest} />,
      name: "Xcircle",
      data: ["xcircle"],
    },
    {
      icon: <X {...rest} />,
      name: "X",
      data: ["x"],
    },
    {
      icon: <Wind {...rest} />,
      name: "Wind",
      data: ["wind"],
    },
    {
      icon: <WifiOff {...rest} />,
      name: "WifiOff",
      data: ["wifioff"],
    },
    {
      icon: <Wifi {...rest} />,
      name: "Wifi",
      data: ["wifi"],
    },
    {
      icon: <Watch {...rest} />,
      name: "Watch",
      data: ["watch", "time"],
    },
    {
      icon: <VolumeX {...rest} />,
      name: "VolumeX",
      data: ["volumex"],
    },
    {
      icon: <Payment {...rest} />,
      name: "Payment",
      data: ["Payment", "money"],
    },
    {
      icon: <Volume2 {...rest} />,
      name: "Volume2",
      data: ["volume"],
    },
    {
      icon: <Volume1 {...rest} />,
      name: "Volume1",
      data: ["volume"],
    },
    {
      icon: <Volume {...rest} />,
      name: "Volume",
      data: ["volume"],
    },
    {
      icon: <VoiceMail {...rest} />,
      name: "VoiceMail",
      data: ["voicemail"],
    },
    {
      icon: <VideoOff {...rest} />,
      name: "VideoOff",
      data: ["videooff"],
    },
    {
      icon: <VideoOn {...rest} />,
      name: "VideoOn",
      data: ["videoon"],
    },
    {
      icon: <Users {...rest} />,
      name: "Users",
      data: ["users"],
    },
    {
      icon: <UserX {...rest} />,
      name: "UserX",
      data: ["userx"],
    },
    {
      icon: <Plus {...rest} />,
      name: "Plus",
      data: ["plus"],
    },
    {
      icon: <UserPlus {...rest} />,
      name: "UserPlus",
      data: ["userplus"],
    },
    {
      icon: <UserMinus {...rest} />,
      name: "UserMinus",
      data: ["userminus"],
    },
    {
      icon: <UserCheck {...rest} />,
      name: "UserCheck",
      data: ["usercheck"],
    },
    {
      icon: <User {...rest} />,
      name: "User",
      data: ["user"],
    },
    {
      icon: <UploadCloud {...rest} />,
      name: "UploadCloud",
      data: ["uploadcloud"],
    },
    {
      icon: <Unlock {...rest} />,
      name: "Unlock",
      data: ["unlock"],
    },
    {
      icon: <Underline {...rest} />,
      name: "Underline",
      data: ["underline"],
    },
    {
      icon: <Umbrella {...rest} />,
      name: "Umbrella",
      data: ["umbrella"],
    },
    {
      icon: <Type {...rest} />,
      name: "Type",
      data: ["type"],
    },
    {
      icon: <Twitter {...rest} />,
      name: "Twitter",
      data: ["twitter"],
    },
    {
      icon: <Twitch {...rest} />,
      name: "Twitch",
      data: ["twitch"],
    },
    {
      icon: <Tv {...rest} />,
      name: "Tv",
      data: ["tv"],
    },
    {
      icon: <Truck {...rest} />,
      name: "Truck",
      data: ["truck", "vehicle"],
    },
    {
      icon: <Triangle {...rest} />,
      name: "Triangle",
      data: ["triangle"],
    },
    {
      icon: <TrendingUp {...rest} />,
      name: "TrendingUp",
      data: ["trendingup"],
    },
    {
      icon: <TrendingDown {...rest} />,
      name: "TrendingDown",
      data: ["trendingdown"],
    },
    {
      icon: <Trello {...rest} />,
      name: "Trello",
      data: ["trello"],
    },
    {
      icon: <Trash2 {...rest} />,
      name: "Trash2",
      data: ["trash", "delete"],
    },
    {
      icon: <Trash {...rest} />,
      name: "Trash",
      data: ["trash", "delete"],
    },
    {
      icon: <Tool {...rest} />,
      name: "Tool",
      data: ["tool"],
    },

    {
      icon: <ToggleRight {...rest} />,
      name: "ToggleRight",
      data: ["toggleright"],
    },
    {
      icon: <ToggleLeft {...rest} />,
      name: "ToggleLeft",
      data: ["toggleleft"],
    },
    {
      icon: <ThumbsUp {...rest} />,
      name: "ThumbsUp",
      data: ["thumbsup"],
    },
    {
      icon: <ThumbsDown {...rest} />,
      name: "ThumbsDown",
      data: ["thumbsdown"],
    },
    {
      icon: <Thermometer {...rest} />,
      name: "Thermometer",
      data: ["thermometer"],
    },
    {
      icon: <Terminal {...rest} />,
      name: "Terminal",
      data: ["terminal"],
    },
    {
      icon: <Target {...rest} />,
      name: "Target",
      data: ["target", "goal"],
    },
    {
      icon: <TagIcon {...rest} />,
      name: "TagIcon",
      data: ["tagicon"],
    },
    {
      icon: <Tablet {...rest} />,
      name: "Tablet",
      data: ["tablet"],
    },
    {
      icon: <Table {...rest} />,
      name: "Table",
      data: ["table"],
    },
    {
      icon: <Sunset {...rest} />,
      name: "Sunset",
      data: ["sunset"],
    },
    {
      icon: <Sunrise {...rest} />,
      name: "Sunrise",
      data: ["sunrise"],
    },
    {
      icon: <Sun {...rest} />,
      name: "Sun",
      data: ["sun"],
    },
    {
      icon: <StopCircle {...rest} />,
      name: "StopCircle",
      data: ["stopcircle"],
    },
    {
      icon: <Archive {...rest} />,
      name: "Archive",
      data: ["archive"],
    },
    {
      icon: <Anchor {...rest} />,
      name: "Anchor",
      data: ["anchor"],
    },
    {
      icon: <Aperture {...rest} />,
      name: "Aperture",
      data: ["aperture"],
    },
    {
      icon: <Activity {...rest} />,
      name: "Activity",
      data: ["Activity"],
    },
    {
      icon: <AlignCenter {...rest} />,
      name: "AlignCenter",
      data: ["aligncenter"],
    },
    {
      icon: <AlignJustify {...rest} />,
      name: "AlignJustify",
      data: ["alignjustify"],
    },
    {
      icon: <AlignLeft {...rest} />,
      name: "AlignLeft",
      data: ["alignleft"],
    },
    {
      icon: <AlignRight {...rest} />,
      name: "AlignRight",
      data: ["alignright"],
    },
    {
      icon: <AlertCircle {...rest} />,
      name: "AlertCircle",
      data: ["alertcircle"],
    },
    {
      icon: <AlertOctagon {...rest} />,
      name: "AlertOctagon",
      data: ["alertoctagon"],
    },
    {
      icon: <AlertTriangle {...rest} />,
      name: "AlertTriangle",
      data: ["alerttriangle"],
    },
    {
      icon: <Star {...rest} />,
      name: "Star",
      data: ["star"],
    },
    {
      icon: <Square {...rest} />,
      name: "Square",
      data: ["square"],
    },
    {
      icon: <Speaker {...rest} />,
      name: "Speaker",
      data: ["speaker", "volume"],
    },
    {
      icon: <Smartphone {...rest} />,
      name: "Smartphone",
      data: ["smartphone", "mobile"],
    },
    {
      icon: <Sliders {...rest} />,
      name: "Sliders",
      data: ["sliders"],
    },
    {
      icon: <Smile {...rest} />,
      name: "Smile",
      data: ["smile"],
    },
    {
      icon: <Slash {...rest} />,
      name: "Slash",
      data: ["slash"],
    },
    {
      icon: <Slack {...rest} />,
      name: "Slack",
      data: ["slack"],
    },
    {
      icon: <SkipForward {...rest} />,
      name: "SkipForward",
      data: ["skipforward"],
    },
    {
      icon: <SkipBack {...rest} />,
      name: "SkipBack",
      data: ["skipback"],
    },
    {
      icon: <RadioIcon {...rest} />,
      name: "RadioIcon",
      data: ["radioicon"],
    },
    {
      icon: <Shuffle {...rest} />,
      name: "Shuffle",
      data: ["shuffle"],
    },
    {
      icon: <ShoppingCart {...rest} />,
      name: "ShoppingCart",
      data: ["shoppingcart"],
    },
    {
      icon: <ShoppingBag {...rest} />,
      name: "ShoppingBag",
      data: ["shoppingbag"],
    },
    {
      icon: <ShieldOff {...rest} />,
      name: "ShieldOff",
      data: ["shieldoff"],
    },
    {
      icon: <Shield {...rest} />,
      name: "Shield",
      data: ["shield"],
    },
    {
      icon: <Share2 {...rest} />,
      name: "Share2",
      data: ["share2"],
    },
    {
      icon: <Share {...rest} />,
      name: "Share",
      data: ["share"],
    },
    {
      icon: <Settings {...rest} />,
      name: "Settings",
      data: ["settings"],
    },
    {
      icon: <Server {...rest} />,
      name: "Server",
      data: ["server"],
    },
    {
      icon: <Send {...rest} />,
      name: "Send",
      data: ["send"],
    },
    {
      icon: <Search {...rest} />,
      name: "Search",
      data: ["search"],
    },
    {
      icon: <Scissors {...rest} />,
      name: "Scissors",
      data: ["scissors"],
    },
    {
      icon: <Save {...rest} />,
      name: "Save",
      data: ["save"],
    },
    {
      icon: <Rss {...rest} />,
      name: "Rss",
      data: ["rss"],
    },
    {
      icon: <Bookmark {...rest} />,
      name: "Bookmark",
      data: ["bookmark"],
    },
    {
      icon: <Book {...rest} />,
      name: "Book",
      data: ["book"],
    },
    {
      icon: <BankOpen {...rest} />,
      name: "BankOpen",
      data: ["bankopen"],
    },
    {
      icon: <RotateCw {...rest} />,
      name: "RotateCw",
      data: ["rotatecw"],
    },
    {
      icon: <RotateCcw {...rest} />,
      name: "RotateCcw",
      data: ["rotateccw"],
    },
    {
      icon: <Rewind {...rest} />,
      name: "Rewind",
      data: ["rewind"],
    },
    {
      icon: <Repeat {...rest} />,
      name: "Repeat",
      data: ["repeat"],
    },
    {
      icon: <RefreshCw {...rest} />,
      name: "RefreshCw",
      data: ["refreshcw"],
    },
    {
      icon: <RefreshCcw {...rest} />,
      name: "RefreshCcw",
      data: ["refreshccw"],
    },
    {
      icon: <SidebarIcon {...rest} />,
      name: "Sidebar",
      data: ["sidebar"],
    },
    {
      icon: <Printer {...rest} />,
      name: "Printer",
      data: ["printer"],
    },
    {
      icon: <Power {...rest} />,
      name: "Power",
      data: ["power", "signout", "logout"],
    },
    {
      icon: <Pocket {...rest} />,
      name: "Pocket",
      data: ["pocket"],
    },
    {
      icon: <PlusSquare {...rest} />,
      name: "PlusSquare",
      data: ["plussquare"],
    },
    {
      icon: <PlusCircle {...rest} />,
      name: "PlusCircle",
      data: ["pluscircle"],
    },
    {
      icon: <PlayCircle {...rest} />,
      name: "PlayCircle",
      data: ["playcircle"],
    },
    {
      icon: <Play {...rest} />,
      name: "Play",
      data: ["play"],
    },
    {
      icon: <PieChart {...rest} />,
      name: "PieChart",
      data: ["piechart"],
    },
    {
      icon: <PhoneOutgoing {...rest} />,
      name: "PhoneOutgoing",
      data: ["phoneoutgoing"],
    },
    {
      icon: <PhoneOff {...rest} />,
      name: "PhoneOff",
      data: ["phoneoff"],
    },
    {
      icon: <PhoneMissed {...rest} />,
      name: "PhoneMissed",
      data: ["phonemissed"],
    },
    {
      icon: <PhoneIncoming {...rest} />,
      name: "PhoneIncoming",
      data: ["phoneincoming", "call"],
    },
    {
      icon: <PhoneForwarded {...rest} />,
      name: "PhoneForwarded",
      data: ["PhoneForwarded", "call"],
    },
    {
      icon: <PhoneCall {...rest} />,
      name: "PhoneCall",
      data: ["phonecall"],
    },
    {
      icon: <Phone {...rest} />,
      name: "Phone",
      data: ["phone", "call"],
    },
    {
      icon: <Percent {...rest} />,
      name: "Percent",
      data: ["percent"],
    },
    {
      icon: <PenTool {...rest} />,
      name: "PenTool",
      data: ["pentool"],
    },
    {
      icon: <PauseCircle {...rest} />,
      name: "PauseCircle",
      data: ["pausecircle"],
    },
    {
      icon: <Pause {...rest} />,
      name: "Pause",
      data: ["pause"],
    },
    {
      icon: <PaperClip {...rest} />,
      name: "PaperClip",
      data: ["paperclip"],
    },
    {
      icon: <Package {...rest} />,
      name: "Package",
      data: ["package"],
    },
    {
      icon: <Octagon {...rest} />,
      name: "Octagon",
      data: ["octagon"],
    },
    {
      icon: <Navigation2 {...rest} />,
      name: "Navigation2",
      data: ["navigation2"],
    },
    {
      icon: <Navigation {...rest} />,
      name: "Navigation",
      data: ["navigation"],
    },
    {
      icon: <Music {...rest} />,
      name: "Music",
      data: ["music", "player"],
    },
    {
      icon: <Move {...rest} />,
      name: "Move",
      data: ["move"],
    },
    {
      icon: <MousePointer {...rest} />,
      name: "MousePointer",
      data: ["mousepointer"],
    },
    {
      icon: <MoreVertical {...rest} />,
      name: "MoreVertical",
      data: ["morevertical"],
    },
    {
      icon: <MoreHorizontal {...rest} />,
      name: "MoreHorizontal",
      data: ["morehorizontal"],
    },
    {
      icon: <Moon {...rest} />,
      name: "Moon",
      data: ["moon"],
    },
    {
      icon: <Monitor {...rest} />,
      name: "Monitor",
      data: ["monitor"],
    },
    {
      icon: <MinusSquare {...rest} />,
      name: "MinusSquare",
      data: ["minussquare"],
    },
    {
      icon: <MinusCircle {...rest} />,
      name: "MinusCircle",
      data: ["minuscircle"],
    },
    {
      icon: <Minus {...rest} />,
      name: "Minus",
      data: ["minus"],
    },
    {
      icon: <Minimize2 {...rest} />,
      name: "Minimize2",
      data: ["minimize2"],
    },
    {
      icon: <Minimize {...rest} />,
      name: "Minimize",
      data: ["minimize"],
    },
    {
      icon: <MicOff {...rest} />,
      name: "MicOff",
      data: ["micOff"],
    },
    {
      icon: <Mic {...rest} />,
      name: "Mic",
      data: ["mic"],
    },
    {
      icon: <MessageSquare {...rest} />,
      name: "MessageSquare",
      data: ["messagesquare"],
    },
    {
      icon: <MessageCircle {...rest} />,
      name: "MessageCircle",
      data: ["messagecircle"],
    },
    {
      icon: <Menu {...rest} />,
      name: "Menu",
      data: ["menu", "hamburger"],
    },
    {
      icon: <Meh {...rest} />,
      name: "Meh",
      data: ["meh"],
    },
    {
      icon: <Maximize2 {...rest} />,
      name: "Maximize2",
      data: ["maximize2"],
    },
    {
      icon: <Maximize {...rest} />,
      name: "Maximize",
      data: ["maximize"],
    },
    {
      icon: <MapPin {...rest} />,
      name: "MapPin",
      data: ["mappin"],
    },
    {
      icon: <Map {...rest} />,
      name: "Map",
      data: ["map"],
    },
    {
      icon: <Mail {...rest} />,
      name: "Mail",
      data: ["mail"],
    },
    {
      icon: <Logout {...rest} />,
      name: "Logout",
      data: ["logout", "signout"],
    },
    {
      icon: <LogIn {...rest} />,
      name: "LogIn",
      data: ["login", "signin"],
    },
    {
      icon: <Lock {...rest} />,
      name: "Lock",
      data: ["lock"],
    },
    {
      icon: <LoaderIcon {...rest} />,
      name: "LoaderIcon",
      data: ["loadericon"],
    },
    {
      icon: <ListIcon {...rest} />,
      name: "ListIcon",
      data: ["list"],
    },
    {
      icon: <LinkedIn {...rest} />,
      name: "LinkedIn",
      data: ["linkedin"],
    },
    {
      icon: <Link2 {...rest} />,
      name: "Link2",
      data: ["link2"],
    },
    {
      icon: <Link {...rest} />,
      name: "Link",
      data: ["link"],
    },
    {
      icon: <LifeBuoy {...rest} />,
      name: "LifeBuoy",
      data: ["lifebuoy"],
    },
    {
      icon: <Layout {...rest} />,
      name: "Layout",
      data: ["layout"],
    },
    {
      icon: <Italic {...rest} />,
      name: "Italic",
      data: ["italic"],
    },
    {
      icon: <Instagram {...rest} />,
      name: "Instagram",
      data: ["instagram"],
    },
    {
      icon: <Info {...rest} />,
      name: "Info",
      data: ["info"],
    },
    {
      icon: <Inbox {...rest} />,
      name: "Inbox",
      data: ["inbox"],
    },
    {
      icon: <Image {...rest} />,
      name: "Image",
      data: ["image"],
    },
    {
      icon: <Home {...rest} />,
      name: "Home",
      data: ["home"],
    },
    {
      icon: <Hexagon {...rest} />,
      name: "Hexagon",
      data: ["hexagon"],
    },
    {
      icon: <HelpCircle {...rest} />,
      name: "HelpCircle",
      data: ["helpcircle"],
    },
    {
      icon: <Heart {...rest} />,
      name: "Heart",
      data: ["heart"],
    },
    {
      icon: <HeadPhones {...rest} />,
      name: "HeadPhones",
      data: ["headphones"],
    },
    {
      icon: <Hash {...rest} />,
      name: "Hash",
      data: ["hash"],
    },
    {
      icon: <HardDrive {...rest} />,
      name: "HardDrive",
      data: ["harddrive"],
    },
    {
      icon: <Grid {...rest} />,
      name: "Grid",
      data: ["grid"],
    },
    {
      icon: <Globe {...rest} />,
      name: "Globe",
      data: ["globe"],
    },
    {
      icon: <Gitlab {...rest} />,
      name: "Gitlab",
      data: ["gitlab"],
    },
    {
      icon: <Github {...rest} />,
      name: "Github",
      data: ["github"],
    },
    {
      icon: <GitPullRequest {...rest} />,
      name: "GitPullRequest",
      data: ["gitpullrequest"],
    },
    {
      icon: <GitMerge {...rest} />,
      name: "GitMerge",
      data: ["gitmerge"],
    },
    {
      icon: <GitCommit {...rest} />,
      name: "GitCommit",
      data: ["gitcommit"],
    },
    {
      icon: <GitBranch {...rest} />,
      name: "GitBranch",
      data: ["gitbranch"],
    },
    {
      icon: <Gift {...rest} />,
      name: "Gift",
      data: ["gift"],
    },
    {
      icon: <Frown {...rest} />,
      name: "Frown",
      data: ["frown"],
    },
    {
      icon: <Framer {...rest} />,
      name: "Framer",
      data: ["framer"],
    },
    {
      icon: <FolderPlus {...rest} />,
      name: "FolderPlus",
      data: ["folderplus"],
    },
    {
      icon: <FolderMinus {...rest} />,
      name: "FolderMinus",
      data: ["folderminus"],
    },
    {
      icon: <Folder {...rest} />,
      name: "Folder",
      data: ["folder"],
    },
    {
      icon: <Flag {...rest} />,
      name: "Flag",
      data: ["flag"],
    },
    {
      icon: <FilterIcon {...rest} />,
      name: "FilterIcon",
      data: ["filtericon"],
    },
    {
      icon: <Film {...rest} />,
      name: "Film",
      data: ["film", "movie"],
    },
    {
      icon: <FileText {...rest} />,
      name: "FileText",
      data: ["filetext"],
    },
    {
      icon: <FilePlus {...rest} />,
      name: "FilePlus",
      data: ["fileplus"],
    },
    {
      icon: <FileMinus {...rest} />,
      name: "FileMinus",
      data: ["fileminus"],
    },
    {
      icon: <File {...rest} />,
      name: "File",
      data: ["file"],
    },
    {
      icon: <Figma {...rest} />,
      name: "Figma",
      data: ["figma"],
    },
    {
      icon: <Feather {...rest} />,
      name: "Feather",
      data: ["feather"],
    },
    {
      icon: <FastForward {...rest} />,
      name: "FastForward",
      data: ["fastforward"],
    },
    {
      icon: <Facebook {...rest} />,
      name: "Facebook",
      data: ["facebook"],
    },
    {
      icon: <EyeOff {...rest} />,
      name: "EyeOff",
      data: ["eyeoff"],
    },
    {
      icon: <Eye {...rest} />,
      name: "Eye",
      data: ["eye"],
    },
    {
      icon: <ExternalLink {...rest} />,
      name: "ExternalLink",
      data: ["externallink"],
    },
    {
      icon: <Edit3 {...rest} />,
      name: "Edit3",
      data: ["edit3"],
    },
    {
      icon: <Edit2 {...rest} />,
      name: "Edit2",
      data: ["edit2"],
    },
    {
      icon: <Edit {...rest} />,
      name: "Edit",
      data: ["edit"],
    },
    {
      icon: <Droplet {...rest} />,
      name: "Droplet",
      data: ["droplet"],
    },
    {
      icon: <Dribble {...rest} />,
      name: "Dribble",
      data: ["dribble"],
    },
    {
      icon: <DownloadCloud {...rest} />,
      name: "DownloadCloud",
      data: ["downloadCloud"],
    },
    {
      icon: <Download {...rest} />,
      name: "Download",
      data: ["download"],
    },
    {
      icon: <DollarSign {...rest} />,
      name: "DollarSign",
      data: ["dollarsign"],
    },
    {
      icon: <DivideSquare {...rest} />,
      name: "DivideSquare",
      data: ["dividesquare"],
    },
    {
      icon: <DivideCircle {...rest} />,
      name: "DivideCircle",
      data: ["dividecircle"],
    },
    {
      icon: <Divide {...rest} />,
      name: "Divide",
      data: ["divide"],
    },
    {
      icon: <Disc {...rest} />,
      name: "Disc",
      data: ["disc"],
    },
    {
      icon: <Delete {...rest} />,
      name: "Delete",
      data: ["delete"],
    },
    {
      icon: <Database {...rest} />,
      name: "Database",
      data: ["database", "storage"],
    },
    {
      icon: <Crosshair {...rest} />,
      name: "Crosshair",
      data: ["crosshair"],
    },
    {
      icon: <Crop {...rest} />,
      name: "Crop",
      data: ["crop"],
    },
    {
      icon: <CreditCard {...rest} />,
      name: "CreditCard",
      data: ["creditcard"],
    },
    {
      icon: <Cpu {...rest} />,
      name: "Cpu",
      data: ["cpu"],
    },
    {
      icon: <CornerUpRight {...rest} />,
      name: "CornerUpRight",
      data: ["cornerupright"],
    },
    {
      icon: <CornerUpLeft {...rest} />,
      name: "CornerUpLeft",
      data: ["cornerupleft"],
    },
    {
      icon: <CornerRightUp {...rest} />,
      name: "CornerRightUp",
      data: ["cornerrightup"],
    },
    {
      icon: <CornerRightDown {...rest} />,
      name: "CornerRightDown",
      data: ["cornerrightdown"],
    },
    {
      icon: <CornerLeftUp {...rest} />,
      name: "CornerLeftUp",
      data: ["cornerleftup"],
    },
    {
      icon: <CornerLeftDown {...rest} />,
      name: "CornerLeftDown",
      data: ["cornerleftdown"],
    },
    {
      icon: <CornerDownRight {...rest} />,
      name: "CornerDownRight",
      data: ["cornerdownright"],
    },
    {
      icon: <CornerDownLeft {...rest} />,
      name: "CornerDownLeft",
      data: ["cornerdownleft"],
    },
    {
      icon: <Copy {...rest} />,
      name: "Copy",
      data: ["copy"],
    },
    {
      icon: <Compass {...rest} />,
      name: "Compass",
      data: ["compass"],
    },
    {
      icon: <Command {...rest} />,
      name: "Command",
      data: ["command"],
    },
    {
      icon: <Award {...rest} />,
      name: "Award",
      data: ["Award"],
    },
    {
      icon: <Columns {...rest} />,
      name: "Columns",
      data: ["columns"],
    },
    {
      icon: <Coffee {...rest} />,
      name: "Coffee",
      data: ["coffee"],
    },
    {
      icon: <CodeSandBox {...rest} />,
      name: "CodeSandBox",
      data: ["codesandBox"],
    },
    {
      icon: <CodePen {...rest} />,
      name: "CodePen",
      data: ["codepen"],
    },
    {
      icon: <Code {...rest} />,
      name: "Code",
      data: ["code"],
    },
    {
      icon: <CloudSnow {...rest} />,
      name: "CloudSnow",
      data: ["cloudsnow"],
    },
    {
      icon: <CloudRain {...rest} />,
      name: "CloudRain",
      data: ["cloudrain"],
    },
    {
      icon: <CloudOff {...rest} />,
      name: "CloudOff",
      data: ["cloudoff"],
    },
    {
      icon: <CloudLightning {...rest} />,
      name: "CloudLightning",
      data: ["cloudlightning"],
    },
    {
      icon: <CloudDrizzle {...rest} />,
      name: "CloudDrizzle",
      data: ["clouddrizzle"],
    },
    {
      icon: <Cloud {...rest} />,
      name: "Cloud",
      data: ["cloud"],
    },
    {
      icon: <Clock {...rest} />,
      name: "Clock",
      data: ["clock", "time", "watch"],
    },
    {
      icon: <Clipboard {...rest} />,
      name: "Clipboard",
      data: ["clipboard"],
    },
    {
      icon: <Circle {...rest} />,
      name: "Circle",
      data: ["circle"],
    },
    {
      icon: <Chrome {...rest} />,
      name: "Chrome",
      data: ["chrome", "google"],
    },
    {
      icon: <ChevronsUp {...rest} />,
      name: "ChevronsUp",
      data: ["chevronsup", "arrowup"],
    },
    {
      icon: <ChevronsRight {...rest} />,
      name: "ChevronsRight",
      data: ["chevronsright", "arrowright"],
    },
    {
      icon: <ChevronLeft {...rest} />,
      name: "ChevronLeft",
      data: ["chevronleft", "arrowleft"],
    },
    {
      icon: <ChevronsLeft {...rest} />,
      name: "ChevronsLeft",
      data: ["chevronsleft", "arrowleft"],
    },
    {
      icon: <ChevronsDown {...rest} />,
      name: "ChevronsDown",
      data: ["chevronsdown", "arrowdown"],
    },
    {
      icon: <ChevronUp {...rest} />,
      name: "ChevronUp",
      data: ["chevronup", "arrowup"],
    },
    {
      icon: <ChevronDown {...rest} />,
      name: "ChevronDown",
      data: ["chevrondown", "arrowdown"],
    },
    {
      icon: <ChevronRight {...rest} />,
      name: "ChevronRight",
      data: ["chevronright", "arrowright"],
    },
    {
      icon: <CheckSquare {...rest} />,
      name: "CheckSquare",
      data: ["checksquare"],
    },
    {
      icon: <CheckCircle {...rest} />,
      name: "CheckCircle",
      data: ["checkcircle"],
    },
    {
      icon: <Check {...rest} />,
      name: "Check",
      data: ["check"],
    },
    {
      icon: <Cast {...rest} />,
      name: "Cast",
      data: ["cast"],
    },
    {
      icon: <CameraOff {...rest} />,
      name: "CameraOff",
      data: ["cameraoff"],
    },
    {
      icon: <Camera {...rest} />,
      name: "Camera",
      data: ["camera"],
    },
    {
      icon: <Calender {...rest} />,
      name: "Calender",
      data: ["calender", "date"],
    },
    {
      icon: <BriefCase {...rest} />,
      name: "BriefCase",
      data: ["briefcase"],
    },
    {
      icon: <Box {...rest} />,
      name: "Box",
      data: ["box"],
    },
    {
      icon: <ProductDelivery {...rest} />,
      name: "ProductDelivery",
      data: ["productdelivery"],
    },
    {
      icon: <Discount {...rest} />,
      name: "Discount",
      data: ["discount"],
    },
    {
      icon: <Billing {...rest} />,
      name: "Billing",
      data: ["billing"],
    },
    {
      icon: <ProductSuccessful {...rest} />,
      name: "ProductSuccessful",
      data: ["productsuccessful"],
    },
    {
      icon: <Campaign {...rest} />,
      name: "Campaign",
      data: ["campaign"],
    },
    {
      icon: <Analytics {...rest} />,
      name: "Analytics",
      data: ["analytics"],
    },
    {
      icon: <Store {...rest} />,
      name: "Store",
      data: ["store"],
    },
    {
      icon: <Payment1 {...rest} />,
      name: "Payment1",
      data: ["payment1", "bill"],
    },
    {
      icon: <Theme {...rest} />,
      name: "Theme",
      data: ["theme"],
    },
    {
      icon: <Transaction {...rest} />,
      name: "Transaction",
      data: ["transaction"],
    },
    {
      icon: <BulkOrders {...rest} />,
      name: "BulkOrders",
      data: ["bulkorders"],
    },
    {
      icon: <BulkProducts {...rest} />,
      name: "BulkProducts",
      data: ["bulkproducts"],
    },
    {
      icon: <AbandonedCart {...rest} />,
      name: "AbandonedCart",
      data: ["abandonedcart"],
    },
    {
      icon: <Activities {...rest} />,
      name: "Activities",
      data: ["activities"],
    },
    {
      icon: <AddProduct {...rest} />,
      name: "AddProduct",
      data: ["addproduct"],
    },
    {
      icon: <Apps {...rest} />,
      name: "Apps",
      data: ["apps"],
    },
    {
      icon: <Wallet {...rest} />,
      name: "Wallet",
      data: ["wallet"],
    },
    {
      icon: <ReturnProduct {...rest} />,
      name: "ReturnProduct",
      data: ["returnproduct"],
    },
    {
      icon: <List1 {...rest} />,
      name: "List1",
      data: ["list1"],
    },
    {
      icon: <Money {...rest} />,
      name: "Money",
      data: ["money", "amount"],
    },
    {
      icon: <Rupee {...rest} />,
      name: "Rupee",
      data: ["rupee", "paisa"],
    },
    {
      icon: <Yen {...rest} />,
      name: "Yen",
      data: ["yen"],
    },
    {
      icon: <Bitcoin {...rest} />,
      name: "Bitcoin",
      data: ["bitcoin"],
    },
    {
      icon: <Dollar {...rest} />,
      name: "Dollar",
      data: ["dollar"],
    },
    {
      icon: <Euro {...rest} />,
      name: "Euro",
      data: ["euro"],
    },
    {
      icon: <Pound {...rest} />,
      name: "Pound",
      data: ["pound"],
    },
    {
      icon: <Bluetooth {...rest} />,
      name: "Bluetooth",
      data: ["Bluetooth"],
    },
    {
      icon: <Ruble {...rest} />,
      name: "Ruble",
      data: ["ruble"],
    },
    {
      icon: <Session {...rest} />,
      name: "Session",
      data: ["session"],
    },
    {
      icon: <Backspace {...rest} />,
      name: "Backspace",
      data: ["backspace"],
    },
    {
      icon: <Checklist {...rest} />,
      name: "Checklist",
      data: ["checklist"],
    },
    {
      icon: <DataVisualization {...rest} />,
      name: "DataVisualization",
      data: ["datavisualization"],
    },
    {
      icon: <DragAndDrop {...rest} />,
      name: "DragAndDrop",
      data: ["draganddrop"],
    },
    {
      icon: <Drag {...rest} />,
      name: "Drag",
      data: ["drag"],
    },
    {
      icon: <Exchange {...rest} />,
      name: "Exchange",
      data: ["exchange"],
    },
    {
      icon: <Inventory {...rest} />,
      name: "Inventory",
      data: ["inventory"],
    },
    {
      icon: <Newsletter {...rest} />,
      name: "Newsletter",
      data: ["newsletter"],
    },
    {
      icon: <Hint {...rest} />,
      name: "Hint",
      data: ["hint"],
    },
    {
      icon: <Event {...rest} />,
      name: "Event",
      data: ["event"],
    },
    {
      icon: <OnlineStore {...rest} />,
      name: "OnlineStore",
      data: ["onlinestore"],
    },
    {
      icon: <Logout1 {...rest} />,
      name: "Logout1",
      data: ["logout1", "signout"],
    },
    {
      icon: <OrderStatus {...rest} />,
      name: "OrderStatus",
      data: ["orderstatus"],
    },
    {
      icon: <CartAdded {...rest} />,
      name: "CartAdded",
      data: ["cartsdded"],
    },
    {
      icon: <Tracking {...rest} />,
      name: "Tracking",
      data: ["tracking"],
    },
    {
      icon: <WriteReview {...rest} />,
      name: "WriteReview",
      data: ["writereview"],
    },
    {
      icon: <Ticket {...rest} />,
      name: "Ticket",
      data: ["ticket"],
    },
    {
      icon: <Bank {...rest} />,
      name: "Bank",
      data: ["bank"],
    },
    {
      icon: <Report {...rest} />,
      name: "Report",
      data: ["report"],
    },
    {
      icon: <Pin {...rest} />,
      name: "Pin",
      data: ["pin"],
    },
    {
      icon: <Refund {...rest} />,
      name: "Refund",
      data: ["refund"],
    },
    {
      icon: <Member {...rest} />,
      name: "Member",
      data: ["member"],
    },
    {
      icon: <Bell {...rest} />,
      name: "Bell",
      data: ["bell", "notification", "alert"],
    },
    {
      icon: <BellOff {...rest} />,
      name: "BellOff",
      data: ["belloff", "notification", "alert"],
    },
    {
      icon: <Barcode {...rest} />,
      name: "Barcode",
      data: ["barcode"],
    },
    {
      icon: <Variants {...rest} />,
      name: "Variants",
      data: ["variants"],
    },
    {
      icon: <Bug {...rest} />,
      name: "Bug",
      data: ["bug"],
    },
    {
      icon: <Language {...rest} />,
      name: "Language",
      data: ["language"],
    },
    {
      icon: <Categories {...rest} />,
      name: "Categories",
      data: ["categories"],
    },
    {
      icon: <Connect {...rest} />,
      name: "Connect",
      data: ["connect"],
    },
    {
      icon: <CardEdit {...rest} />,
      name: "CardEdit",
      data: ["cardedit"],
    },
    {
      icon: <Embed {...rest} />,
      name: "Embed",
      data: ["embed"],
    },
    {
      icon: <CardLock {...rest} />,
      name: "CardLock",
      data: ["cardlock"],
    },
  ];
  return Icons;
};
